# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxHW' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxHW

  pod 'SnapKit', '~> 4.0.0'
  pod 'RxSwift', '~> 4.0'
  pod 'RxCocoa', '~> 4.0'
  pod 'RxDataSources', '~> 3.0'

  target 'RxHWTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RxHWUITests' do
    # Pods for testing
  end

end
